name: build

on:
  pull_request:
  push:
    branches:
      - develop
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm install
    - env:
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      if: github.event_name == 'pull_request'
      name: configure environment for pull request
      run: |
        echo ::set-env name=GIT_BRANCH::$GITHUB_HEAD_REF
        echo ::set-env name=GIT_COMMIT_SHA::$HEAD_SHA
    - env:
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      if: github.event_name == 'push'
      name: configure environment for push
      run: |
        echo ::set-env name=GIT_BRANCH::${GITHUB_REF#refs/heads/}
        echo ::set-env name=GIT_COMMIT_SHA::$GITHUB_SHA
    - name: prepare test reporter
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build
    - run: npm run all
    - env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      name: upload coverage
      run: ./cc-test-reporter after-build --prefix github.com/jbrunton/gha-installer
    - name: check build up to date
      run: git diff --exit-code --stat HEAD
