name: examples

on:
  pull_request:
  push:
    branches:
      - develop
      - 'releases/*'

jobs:

  example-single-app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install && npm run build
    - run: cd ./examples/single-app && npm install && npm run build
    - name: install latest version
      uses: ./examples/single-app
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: install specific version
      uses: ./examples/single-app
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        version: 0.1.5
    - name: verify installed
      run: npm run verify:output "gflows version" "gflows version 0.1.5" 

  example-multi-app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install && npm run build
    - run: cd ./examples/multi-app && npm install && npm run build
    - uses: ./examples/multi-app
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ytt: 0.28.0
    - name: verify installed
      run: |
        npm run verify:installed ytt kbld kapp kwt imgpkg vendir
        npm run verify:output "ytt version" "ytt version 0.28.0" 
