name: examples

on:
  pull_request:
  push:
    branches:
      - develop
      - 'releases/*'

jobs:

  single-app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install && npm run build
    - run: cd ./examples/single-app && npm install
    - uses: ./examples/single-app
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: gflows version

  multi-app-multi-platform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install && npm run build
    - run: cd ./examples/multi-app-multi-platform && npm install
    - uses: ./examples/multi-app-multi-platform
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: ytt version
